### ISSUE TITLE
fix: failed test for jest monorepo update pull request

### ISSUE THREAD

**Issue by yamanoku** [yamanoku/vue-visually-hidden#27]
https://github.com/yamanoku/vue-visually-hidden/pull/19

```bash
> jest

FAIL src/components/VisuallyHidden.spec.ts
  ● Test suite failed to run

    TypeError: Cannot destructure property 'config' of 'undefined' as it is undefined.

      at Object.getCacheKey (node_modules/vue-jest/lib/index.js:10:7)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:280:41)
      at ScriptTransformer._getFileCachePath (node_modules/@jest/transform/build/ScriptTransformer.js:351:27)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:588:32)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:758:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:815:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.289 s
```

**Comment by yamanoku** [comment]
it use `@vue/vue3-jest@27`
